In [1]:
import pandas as pd

CONVERT = pd.read_csv('/Users/xishou/pyprojects/predict_Lottery_ticket/lottery/data/convert.csv')
print("数据总量: %d ." % len(CONVERT))
CONVERT

数据总量: 2732 .

,期数,红_1_exist,红_1_总次数_10,红_1_平均遗漏值_10,红_1_最大遗漏值_10,红_1_本次遗漏_10,红_1_上次遗漏_10,红_1_总次数_30,红_1_平均遗漏值_30,红_1_最大遗漏值_30,...,蓝_16_总次数_50,蓝_16_平均遗漏值_50,蓝_16_最大遗漏值_50,蓝_16_本次遗漏_50,蓝_16_上次遗漏_50,蓝_16_总次数_100,蓝_16_平均遗漏值_100,蓝_16_最大遗漏值_100,蓝_16_本次遗漏_100,蓝_16_上次遗漏_100
0,21088,0,2,2.67,7,7,1,9,2.1,7,...,5,7.5,23,23,0,7,11.62,32,23,0
1,21087,0,2,2.67,6,6,1,9,2.1,6,...,5,7.5,22,22,0,7,11.62,32,22,0
2,21086,0,2,2.67,5,5,1,9,2.1,5,...,5,7.5,21,21,0,7,11.62,32,21,0
3,21085,0,2,2.67,4,4,1,9,2.1,5,...,5,7.5,20,20,0,7,11.62,32,20,0
4,21084,0,2,2.67,4,3,1,9,2.1,5,...,5,7.5,19,19,0,7,11.62,32,19,0
...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...
2727,3005,0,1,2.00,2,2,2,1,2.0,2,...,2,1.0,2,0,1,2,1.00,2,0,1
2728,3004,0,1,1.50,2,1,2,1,1.5,2,...,1,1.5,2,1,2,1,1.50,2,1,2
2729,3003,1,1,1.00,2,0,2,1,1.0,2,...,1,1.0,2,0,2,1,1.00,2,0,2
2730,3002,0,0,2.00,2,2,0,0,2.0,2,...,0,2.0,2,2,0,0,2.00,2,2,0
2731,3001,0,0,1.00,1,1,0,0,1.0,1,...,0,1.0,1,1,0,0,1.00,1,1,0

In [2]:

URL = "https://datachart.500.com/ssq/history/"
path = "newinc/history.php?start={}&end="

BOLL_NAME = [
    "红球号码_1",
    "红球号码_2",
    "红球号码_3",
    "红球号码_4",
    "红球号码_5",
    "红球号码_6",
    "蓝球"
]

BALL_ENUM = None

ATTRIBUTE_ISSUE = '期数'
X_ATTRIBUTES = None
Y_ATTRIBUTES = None

RECENT_COUNTS = [10, 30, 50, 100]

def init():
    global BALL_ENUM, X_ATTRIBUTES, Y_ATTRIBUTES, RECENT_COUNTS
    if BALL_ENUM is not None:
        return
    BALL_ENUM = []
    X_ATTRIBUTES = {}
    Y_ATTRIBUTES = {}
    for ball_type in ['红', '蓝']:
        for ball_num in range(1, 34):
            if ball_type == '蓝' and ball_num > 16:
                break
            BALL_ENUM.append((ball_type, ball_num))
            X_ATTRIBUTES[ball_type + '_' + str(ball_num)] = []
            for suffix in ['总次数_', '平均遗漏值_', '最大遗漏值_', '本次遗漏_', '上次遗漏_']:
                for recent_count in RECENT_COUNTS:
                    X_ATTRIBUTES[ball_type + '_' + str(ball_num)].append(
                        ball_type + '_' + str(ball_num) + '_' + suffix + str(recent_count))
            Y_ATTRIBUTES[ball_type + '_' + str(ball_num)] = ball_type + '_' + str(ball_num) + '_exist'

init()

In [3]:
ball = ('蓝', 1)
key = ball[0] + '_' + str(ball[1])
offset=2
test_x = [ATTRIBUTE_ISSUE,X_ATTRIBUTES[key][0]]
# CONVERT[test_x][offset:-1]
#CONVERT[[ATTRIBUTE_ISSUE,X_ATTRIBUTES[key][0]]][offset+1:]
test_x
CONVERT[test_x][offset:]

NameError: name 'process_data' is not defined

In [4]:
offset=0
history = {}
newest_d_x = {}
x_attributes = []
y_attributes = []
history[ATTRIBUTE_ISSUE] = CONVERT[ATTRIBUTE_ISSUE].values[offset+1:]
newest_d_x[ATTRIBUTE_ISSUE] = CONVERT[ATTRIBUTE_ISSUE].values[offset]
for ball_item in BALL_ENUM:
    k = ball_item[0] + '_' + str(ball_item[1])
    history[Y_ATTRIBUTES[k]] = CONVERT[Y_ATTRIBUTES[k]][offset:-1].values
    for column in X_ATTRIBUTES[k]:
        history[column] = CONVERT[column][offset+1:].values
        newest_d_x[column] = [CONVERT[column][offset]]
    x_attributes += X_ATTRIBUTES[k]
    y_attributes.append(Y_ATTRIBUTES[k])
pd.DataFrame(history, columns=[ATTRIBUTE_ISSUE] + y_attributes + x_attributes)

,期数,红_1_exist,红_2_exist,红_3_exist,红_4_exist,红_5_exist,红_6_exist,红_7_exist,红_8_exist,红_9_exist,...,蓝_16_最大遗漏值_50,蓝_16_最大遗漏值_100,蓝_16_本次遗漏_10,蓝_16_本次遗漏_30,蓝_16_本次遗漏_50,蓝_16_本次遗漏_100,蓝_16_上次遗漏_10,蓝_16_上次遗漏_30,蓝_16_上次遗漏_50,蓝_16_上次遗漏_100
0,21087,0,0,0,1,0,0,0,0,0,...,22,32,10,22,22,22,0,0,0,0
1,21086,0,1,0,0,0,0,0,0,0,...,21,32,10,21,21,21,0,0,0,0
2,21085,0,0,0,0,0,1,0,1,0,...,20,32,10,20,20,20,0,0,0,0
3,21084,0,0,0,0,1,1,1,0,0,...,19,32,10,19,19,19,0,0,0,0
4,21083,0,0,0,0,1,0,1,0,1,...,18,32,10,18,18,18,0,0,0,0
...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...
2726,3005,1,0,1,0,0,0,0,0,0,...,2,2,0,0,0,0,1,1,1,1
2727,3004,0,0,0,1,0,1,0,0,0,...,2,2,1,1,1,1,2,2,2,2
2728,3003,0,0,0,1,0,1,1,0,0,...,2,2,0,0,0,0,2,2,2,2
2729,3002,1,0,0,0,0,0,1,0,0,...,2,2,2,2,2,2,0,0,0,0
2730,3001,0,0,0,1,0,0,0,0,1,...,1,1,1,1,1,1,0,0,0,0

In [5]:
def process_data(converted_data, offset):
    history = {}
    newest_d_x = {}
    x_attributes = []
    y_attributes = []
    history[ATTRIBUTE_ISSUE] = converted_data[ATTRIBUTE_ISSUE].values[offset+1:]
    newest_d_x[ATTRIBUTE_ISSUE] = converted_data[ATTRIBUTE_ISSUE].values[offset]
    for ball_item in BALL_ENUM:
        k = ball_item[0] + '_' + str(ball_item[1])
        history[Y_ATTRIBUTES[k]] = converted_data[Y_ATTRIBUTES[k]][offset:-1].values
        for column in X_ATTRIBUTES[k]:
            history[column] = converted_data[column][offset+1:].values
            newest_d_x[column] = [converted_data[column][offset]]
        x_attributes += X_ATTRIBUTES[k]
        y_attributes.append(Y_ATTRIBUTES[k])
    return pd.DataFrame(history, columns=[ATTRIBUTE_ISSUE] + y_attributes + x_attributes), pd.DataFrame(
        newest_d_x, columns=[ATTRIBUTE_ISSUE] + x_attributes)

data, newest_X = process_data(CONVERT, 0)
data

,期数,红_1_exist,红_2_exist,红_3_exist,红_4_exist,红_5_exist,红_6_exist,红_7_exist,红_8_exist,红_9_exist,...,蓝_16_最大遗漏值_50,蓝_16_最大遗漏值_100,蓝_16_本次遗漏_10,蓝_16_本次遗漏_30,蓝_16_本次遗漏_50,蓝_16_本次遗漏_100,蓝_16_上次遗漏_10,蓝_16_上次遗漏_30,蓝_16_上次遗漏_50,蓝_16_上次遗漏_100
0,21087,0,0,0,1,0,0,0,0,0,...,22,32,10,22,22,22,0,0,0,0
1,21086,0,1,0,0,0,0,0,0,0,...,21,32,10,21,21,21,0,0,0,0
2,21085,0,0,0,0,0,1,0,1,0,...,20,32,10,20,20,20,0,0,0,0
3,21084,0,0,0,0,1,1,1,0,0,...,19,32,10,19,19,19,0,0,0,0
4,21083,0,0,0,0,1,0,1,0,1,...,18,32,10,18,18,18,0,0,0,0
...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...
2726,3005,1,0,1,0,0,0,0,0,0,...,2,2,0,0,0,0,1,1,1,1
2727,3004,0,0,0,1,0,1,0,0,0,...,2,2,1,1,1,1,2,2,2,2
2728,3003,0,0,0,1,0,1,1,0,0,...,2,2,0,0,0,0,2,2,2,2
2729,3002,1,0,0,0,0,0,1,0,0,...,2,2,2,2,2,2,0,0,0,0
2730,3001,0,0,0,1,0,0,0,0,1,...,1,1,1,1,1,1,0,0,0,0

In [6]:
from sklearn.model_selection import train_test_split

train_set, test_set = train_test_split(data, test_size=0.2, random_state=42)

In [13]:
len(data.keys())

1030

In [61]:
import tensorflow as tf
from tensorflow.keras import Sequential
from tensorflow.keras.layers import LSTM
from tensorflow.keras.layers import Dense


vocab_size = 21
embedding_dim=64
model = tf.keras.Sequential([ 
    tf.keras.layers.LSTM(embedding_dim,input_shape=(1,vocab_size)),
    tf.keras.layers.Dense(embedding_dim, activation='relu'),
    tf.keras.layers.Dense(1, activation='softmax')
])
model.compile(loss='sparse_categorical_crossentropy', optimizer='adam', metrics=['accuracy'])
model.summary()

Model: "sequential_10"
_________________________________________________________________
Layer (type)                 Output Shape              Param #
=================================================================
lstm_10 (LSTM)               (None, 64)                22016
_________________________________________________________________
dense_19 (Dense)             (None, 64)                4160
_________________________________________________________________
dense_20 (Dense)             (None, 1)                 65
=================================================================
Total params: 26,241
Trainable params: 26,241
Non-trainable params: 0
_________________________________________________________________

In [20]:
ball = ('蓝', 1)
key = ball[0] + '_' + str(ball[1])
train_set_x = train_set[[ATTRIBUTE_ISSUE] + X_ATTRIBUTES[key]].values
train_set_y = train_set[Y_ATTRIBUTES[key]].values
test_set_x = test_set[[ATTRIBUTE_ISSUE] + X_ATTRIBUTES[key]].values
test_set_y = test_set[Y_ATTRIBUTES[key]].values

In [49]:
train_set[[ATTRIBUTE_ISSUE] + X_ATTRIBUTES[key]]
train_set[Y_ATTRIBUTES[key]]
train_set[[ATTRIBUTE_ISSUE] + X_ATTRIBUTES[key]]

,期数,蓝_1_总次数_10,蓝_1_总次数_30,蓝_1_总次数_50,蓝_1_总次数_100,蓝_1_平均遗漏值_10,蓝_1_平均遗漏值_30,蓝_1_平均遗漏值_50,蓝_1_平均遗漏值_100,蓝_1_最大遗漏值_10,...,蓝_1_最大遗漏值_50,蓝_1_最大遗漏值_100,蓝_1_本次遗漏_10,蓝_1_本次遗漏_30,蓝_1_本次遗漏_50,蓝_1_本次遗漏_100,蓝_1_上次遗漏_10,蓝_1_上次遗漏_30,蓝_1_上次遗漏_50,蓝_1_上次遗漏_100
347,19025,0,3,5,10,10.00,6.75,7.50,8.18,10,...,16,25,10,12,12,12,0,9,9,9
1807,9099,1,1,1,6,4.50,14.50,24.50,13.43,6,...,43,44,6,6,6,6,3,23,43,44
1114,14024,0,1,4,5,10.00,14.50,9.20,15.83,10,...,23,31,10,23,23,23,0,6,6,6
2072,7141,0,3,4,6,10.00,6.75,9.20,13.43,10,...,16,26,10,16,16,16,0,4,4,4
1075,14063,1,1,2,6,4.50,14.50,16.00,13.43,7,...,28,28,7,7,7,7,2,22,28,28
...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...
1638,10114,2,4,7,9,2.67,5.20,5.38,9.10,5,...,16,23,0,0,0,0,3,3,3,3
1095,14043,0,1,3,6,10.00,14.50,11.75,13.43,10,...,25,31,10,16,16,16,0,13,25,25
1130,14008,1,4,4,5,4.50,5.20,9.20,15.83,7,...,20,38,7,7,7,7,2,6,6,6
1294,12152,1,3,3,6,4.50,6.75,11.75,13.43,8,...,22,64,1,1,1,1,8,21,21,21
860,15126,1,4,6,8,4.50,5.20,6.29,10.22,7,...,12,24,2,2,2,2,7,9,9,9

In [62]:
num_epochs = 10
history = model.fit(train_set_x, 
                    train_set_y, 
                    epochs=num_epochs, 
                    validation_data=(test_set_x, test_set_y), 
                    verbose=2)

ValueError: Error when checking input: expected lstm_10_input to have 3 dimensions, but got array with shape (2184, 21)